apiVersion: v1
kind: Service
metadata:
  prometheus.io/scrape: 'true'
  name: {{ include "cfb-calls.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cfb-calls.name" . }}
    helm.sh/chart: {{ include "cfb-calls.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
    ports:
    - port: {{ .Values.service.servicePort }}
      nodePort: {{ .Values.service.serviceNodePort }}
  selector:
    app.kubernetes.io/name: {{ include "cfb-calls.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
