{{ if .Values.hpa.enabled }}
apiVersion: autoscaling/v1beta2
kind: HorizontalPodAutoScaler
metadata:
  name: "{{ .Chart.Name }}-hpa-policy"
  namespace:
spec:
  scaleTargetRef:
    apiVersion: apps/v2alpha1
    kind: Deployment
    name: "{{ .Chart.Name }}-deployment"
  minReplicas: {{ .Values.hpa.minRelicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: {{ .Values.hpa.metrics.cpu.targetAverageUtilization }}
  - type: Resource
    resource:
      name: memory
      targetAverageUtilization: {{ .Values.hpa.metrics.memory.targetAverageUtilization }}
{{ end }}