apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: {{ include "call-for-blood.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "call-for-blood.name" . }}
    helm.sh/chart: {{ include "call-for-blood.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: frontend
      port: {{ .Values.service.servicePort}}
      nodePort: {{ .Values.service.serviceNodePort }}
    - name: auth
      port: {{ .Values.auth.servicePort }}
      nodePort: {{ .Values.auth.serviceNodePort }}
  selector:
    app.kubernetes.io/name: {{ include "call-for-blood.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
