apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: {{ include "cfb-auth.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "cfb-auth.name" . }}
    helm.sh/chart: {{ include "cfb-auth.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "cfb-auth.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "cfb-auth.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: {{ .Values.service.servicePort }}
          resources:
            requests:
              cpu: "{{ .Values.image.resources.requests.cpu }}"
              memory: "{{ .Values.image.resources.requests.memory }}"
          env:
            - name: PORT
              value: "{{ .Values.service.servicePort }}"